name: aloronsite
version: 1.0.0+1
publish_to: none
description: A offline app for manage field work for Aloronsite project
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.8.4
  get_storage: 2.1.1
  http: 1.1.0
  logger: 2.0.1
  loading_animation_widget: 1.2.0+4
  objectbox: any
  objectbox_flutter_libs: any
  path: 1.8.3
  path_provider: 2.0.15
  cached_network_image: 3.2.3
  animated_bottom_navigation_bar: 1.2.0
  dio: 5.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: any
  objectbox_generator: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

